/**
 * backend/utils/analyticsEvent.js
 *
 * Phase 1 — Event Schema & UUID Strategy
 *
 * This is the foundation of the entire analytics system.
 * Every service that creates an analytics event imports from here.
 *
 * Design decisions (from implementation guide):
 *
 *   1. UUID as primary event_id — generated at the browser at the moment
 *      of user action and passed to the backend. Reused identically for
 *      GA4 and Meta CAPI so both platforms deduplicate against the same key.
 *
 *      Why not deterministic hash?
 *        - Clock skew: client and server timestamps differ by milliseconds,
 *          producing different hashes for the same event.
 *        - Retry idempotency: retries with slightly different timestamps
 *          produce new IDs, breaking deduplication.
 *        - Anonymous → auth transition: userId changes at login, invalidating
 *          any hash that includes it.
 *
 *   2. Deterministic hash fallback — used ONLY for server-only events
 *      (webhooks, cron jobs) where no browser context exists.
 *
 *   3. Three-timestamp pattern:
 *        event_time_client    — browser Date.now() at moment of user action
 *        event_time_server    — server Date.now() when event is received
 *        event_time_processed — set by queue worker when event is dispatched
 *
 *      Server time is canonical for deduplication and ordering.
 *      Client time is preserved for funnel analysis (network delay skews
 *      server timestamps for time-on-step calculations).
 *
 *   4. event_source — "client" | "server"
 *      Essential for debugging duplicate events. When you see the same
 *      event_id twice, event_source tells you which one is the dedup target.
 *
 *   5. schema_version — allows BigQuery schema evolution without breaking
 *      existing queries. Increment when adding required fields.
 */

import crypto from 'crypto';
import { v4 as uuidv4 } from 'uuid';

// ─── UUID VALIDATION ──────────────────────────────────────────────────────────

/**
 * Validates that a string is a well-formed RFC 4122 UUID v4.
 * Used to verify the client-generated UUID before trusting it as event_id.
 *
 * @param {string} id
 * @returns {boolean}
 */
export const isValidUUID = (id) => {
  if (!id || typeof id !== 'string') return false;
  return /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id);
};

// ─── EVENT ID GENERATION ──────────────────────────────────────────────────────

/**
 * generateEventId
 *
 * Primary:  Client-generated UUID passed from the browser.
 *           This is the source of truth for cross-platform deduplication.
 *
 * Fallback: SHA-256 hash of userId + timestamp + eventType.
 *           Used only when no client UUID is available (server-only events).
 *           The hash is truncated to 32 hex chars to stay within GA4/Meta
 *           event_id length constraints while remaining collision-resistant.
 *
 * @param {string|null} clientUUID     - UUID generated by the browser SDK
 * @param {Object}      fallbackParts  - Parts for the hash fallback
 * @param {string}      fallbackParts.userId
 * @param {number}      fallbackParts.timestamp
 * @param {string}      fallbackParts.eventType
 * @returns {string}
 */
export const generateEventId = (clientUUID = null, fallbackParts = {}) => {
  // Primary path: trust the client UUID if it is a valid v4
  if (clientUUID && isValidUUID(clientUUID)) {
    return clientUUID;
  }

  // Fallback path: deterministic hash for server-only events
  const {
    userId    = 'anon',
    timestamp = Date.now(),
    eventType = 'event',
  } = fallbackParts;

  return crypto
    .createHash('sha256')
    .update(`${userId}:${timestamp}:${eventType}`)
    .digest('hex')
    .substring(0, 32); // 32 hex chars = 128 bits — sufficient for collision resistance
};

// ─── EVENT BUILDER ────────────────────────────────────────────────────────────

/**
 * buildAnalyticsEvent
 *
 * Assembles a complete, normalized analytics event object.
 * Every analytics service (GA4, Meta CAPI, BigQuery) consumes this shape.
 * Never send raw controller data to external platforms — always go through
 * this builder so the schema is enforced consistently.
 *
 * @param {Object} params
 * @param {string}      params.eventType        - e.g. "purchase", "checkout_step", "page_view"
 * @param {string|null} params.eventId          - UUID from client or null (fallback will be used)
 * @param {string|null} params.userId           - Authenticated user MongoDB _id as string, or null
 * @param {string|null} params.anonymousId      - First-party anonymous ID from epicstore_anon cookie
 * @param {string|null} params.sessionId        - Rolling session ID from epicstore_sid cookie
 * @param {Object}      params.properties       - Event-specific payload (order data, product data, etc.)
 * @param {Object}      params.attribution      - Full attribution context from req.attribution
 * @param {string|null} params.clientTimestamp  - ISO string from browser at moment of action
 * @param {string}      params.source           - "client" | "server" — origin of the event
 * @returns {Object}   Normalized analytics event ready for queue ingestion
 */
export const buildAnalyticsEvent = ({
  eventType,
  eventId       = null,
  userId        = null,
  anonymousId   = null,
  sessionId     = null,
  properties    = {},
  attribution   = {},
  clientTimestamp = null,
  source        = 'server',
}) => {
  const serverTimestamp = new Date().toISOString();

  // Resolve event_id: client UUID → hash fallback
  const resolvedEventId = generateEventId(eventId, {
    userId:    userId || 'anon',
    timestamp: Date.now(),
    eventType,
  });

  return {
    // ── Identity ────────────────────────────────────────────────────────────
    event_id:     resolvedEventId,
    event_type:   eventType,

    // ── Source & Timing ─────────────────────────────────────────────────────
    // event_source tells you whether this event was emitted by the browser
    // or generated server-side. Critical for debugging duplicate events:
    // when the same event_id appears twice, event_source shows which is the
    // client fire and which is the server fire — GA4/Meta dedup the pair.
    event_source:         source,
    event_time_client:    clientTimestamp || serverTimestamp,
    event_time_server:    serverTimestamp,
    event_time_processed: null, // Set by queue worker (analyticsQueue.js) on dispatch

    // ── User Identity ───────────────────────────────────────────────────────
    // userId is null for pre-auth events. anonymousId persists across the
    // full journey and enables pre→post auth stitching in BigQuery.
    user_id:       userId     || null,
    anonymous_id:  anonymousId || null,
    session_id:    sessionId  || null,

    // ── Event Data ──────────────────────────────────────────────────────────
    properties,

    // ── Attribution ─────────────────────────────────────────────────────────
    // Full attribution context including confidence score and click IDs.
    // Populated by attributionMiddleware.js on every request.
    attribution: {
      source:            attribution.source           || 'direct',
      medium:            attribution.medium           || null,
      campaign:          attribution.campaign         || null,
      referrer:          attribution.referrer         || null,
      landing_page:      attribution.landingPage      || null,
      gclid:             attribution.gclid            || null,
      fbclid:            attribution.fbclid           || null,
      ttclid:            attribution.ttclid           || null,
      confidence_score:  attribution.confidenceScore  ?? null,
      confidence_level:  attribution.confidenceLevel  || null,
      is_reconstructed:  attribution.isReconstructed  || false,
      reconstruction_rule: attribution.reconstructionRule || null,
      device:            attribution.device           || null,
      browser:           attribution.browser          || null,
    },

    // ── Schema Version ──────────────────────────────────────────────────────
    // Increment when adding required fields to the schema.
    // BigQuery partitioned tables use this for schema evolution tracking.
    schema_version: '1.0',
  };
};

// ─── PURCHASE EVENT BUILDER ───────────────────────────────────────────────────

/**
 * buildPurchaseEvent
 *
 * Convenience builder for purchase events — the highest-value event in the
 * system. Wraps buildAnalyticsEvent with the correct properties shape for
 * GA4 e-commerce and Meta CAPI Purchase events.
 *
 * Called from verifyPaymentController after a successful payment.
 *
 * @param {Object} order         - Mongoose Order document (post-save)
 * @param {Object} req           - Express request (for session, attribution, anonymousId)
 * @param {string} [clientUUID]  - UUID sent from frontend at payment initiation
 * @returns {Object}             - Normalized purchase analytics event
 */
export const buildPurchaseEvent = (order, req, clientUUID = null) => {
  return buildAnalyticsEvent({
    eventType:       'purchase',
    eventId:         clientUUID || req.body?.analyticsEventId || null,
    userId:          req.user?._id?.toString() || null,
    anonymousId:     req.anonymousId   || null,
    sessionId:       req.sessionId     || null,
    clientTimestamp: req.body?.clientTimestamp || null,
    source:          'server',
    attribution:     req.attribution   || {},
    properties: {
      // Core purchase data
      order_id:          order._id.toString(),
      payment_reference: order.paymentInfo?.reference,
      revenue:           order.totalPrice,
      currency:          order.paymentInfo?.currency || 'USD',
      tax:               order.taxPrice             || 0,
      shipping:          order.shippingPrice        || 0,

      // Discount data
      coupon:            order.discounts?.codes?.[0]?.code || null,
      discount_amount:   order.discounts?.totalDiscount    || 0,

      // Items
      items: (order.orderItems || []).map(item => ({
        item_id:       item.product?.toString(),
        item_name:     item.name,
        item_category: item.category || 'unknown',
        price:         item.price,
        quantity:      item.quantity,
        line_total:    item.price * item.quantity,
      })),

      // Order metadata
      item_count:     order.orderItems?.length || 0,
      payment_method: order.paymentInfo?.method,
      is_first_purchase: order.analytics?.isFirstPurchase || false,
      purchase_number:   order.analytics?.purchaseNumber  || null,
    },
  });
};

// ─── CHECKOUT FUNNEL EVENT BUILDER ────────────────────────────────────────────

/**
 * buildCheckoutStepEvent
 *
 * Builds a funnel step event for BigQuery funnel_states table and GA4.
 * Called from checkoutController when a step is updated.
 *
 * @param {string} step          - e.g. "shipping_info", "payment_selection"
 * @param {Object} checkout      - Checkout document
 * @param {Object} req           - Express request
 * @param {string} [clientUUID]  - UUID from frontend
 * @returns {Object}
 */
export const buildCheckoutStepEvent = (step, checkout, req, clientUUID = null) => {
  return buildAnalyticsEvent({
    eventType:       'checkout_step',
    eventId:         clientUUID || null,
    userId:          req.user?._id?.toString() || null,
    anonymousId:     req.anonymousId  || null,
    sessionId:       req.sessionId    || null,
    clientTimestamp: req.body?.clientTimestamp || null,
    source:          'server',
    attribution:     req.attribution  || {},
    properties: {
      checkout_id:    checkout._id.toString(),
      step,
      cart_value:     checkout.pricing?.totalPrice || 0,
      item_count:     checkout.items?.length       || 0,
      currency:       checkout.pricing?.currency   || 'USD',
      has_discount:   !!(checkout.discount?.code),
    },
  });
};

// ─── EVENT TYPE CONSTANTS ─────────────────────────────────────────────────────

/**
 * ANALYTICS_EVENTS
 *
 * Canonical list of event types used across the system.
 * Import this when dispatching events to avoid string typos.
 *
 * GA4 mapping: https://developers.google.com/analytics/devguides/collection/protocol/ga4/reference/events
 * Meta mapping: https://developers.facebook.com/docs/meta-pixel/reference
 */
export const ANALYTICS_EVENTS = {
  // Conversion events (highest priority — always sent server-side)
  PURCHASE:          'purchase',
  BEGIN_CHECKOUT:    'begin_checkout',
  ADD_PAYMENT_INFO:  'add_payment_info',

  // Funnel events
  CHECKOUT_STEP:     'checkout_step',
  CHECKOUT_ABANDON:  'checkout_abandon',
  CART_RECOVERY:     'cart_recovery',

  // Engagement events
  ADD_TO_CART:       'add_to_cart',
  REMOVE_FROM_CART:  'remove_from_cart',
  VIEW_ITEM:         'view_item',
  VIEW_ITEM_LIST:    'view_item_list',
  ADD_TO_WISHLIST:   'add_to_wishlist',
  SEARCH:            'search',

  // User events
  LOGIN:             'login',
  SIGN_UP:           'sign_up',
  EMAIL_VERIFIED:    'email_verified',

  // System events
  REFUND:            'refund',
  RETURN_REQUESTED:  'return_requested',
};

// ─── VALIDATION ───────────────────────────────────────────────────────────────

/**
 * validateAnalyticsEvent
 *
 * Validates that a built event has all required fields before it is
 * enqueued. Returns { valid: boolean, errors: string[] }.
 *
 * Call this in development to catch schema issues early.
 * In production the queue will still process events with minor issues
 * but log them to the observability layer.
 *
 * @param {Object} event - Output of buildAnalyticsEvent()
 * @returns {{ valid: boolean, errors: string[] }}
 */
export const validateAnalyticsEvent = (event) => {
  const errors = [];

  if (!event.event_id)   errors.push('event_id is required');
  if (!event.event_type) errors.push('event_type is required');
  if (!event.event_source || !['client', 'server'].includes(event.event_source)) {
    errors.push('event_source must be "client" or "server"');
  }
  if (!event.event_time_server) errors.push('event_time_server is required');
  if (!event.schema_version)    errors.push('schema_version is required');

  // Warn (not error) if both user_id and anonymous_id are null
  // This is valid for some public page_view events but unusual for purchase events
  if (!event.user_id && !event.anonymous_id) {
    errors.push('WARNING: both user_id and anonymous_id are null — event cannot be attributed to any identity');
  }

  return {
    valid:  errors.filter(e => !e.startsWith('WARNING')).length === 0,
    errors,
  };
};

